import express from "express";
import { errorMiddleware } from "./middleware/error.middleware";
import { authenticate } from "./middleware/auth.middleware";
import cookieParser from "cookie-parser";
export const app = express();
import { orderRouter } from "./routers/order.router";
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(authenticate);
app.use("/order", orderRouter);
app.use(errorMiddleware);
